title:              Tan Xifei's Blog
email:              tanxifei@tx648.cn
description:        一个普普通通的电教员，副业拍梯
author:             Tan Xifei
baseurl:            ""
url:                "https://TanXifei.github.io"

# Social Profiles
twitter_username:   
github_username:    TanXifei
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
